#########################################
### Spring Cloud Config Server
#########################################
spring:
  cloud:
    config:
      server:
        composite:
          - type: git
            repos:
              DEV:
                pattern: ',DEV' # Match profile composite,DEV
                                #ALWAYS PLACE DEV PROFILES AT END
                                # TODO: When we move to AppService use 'DEV' only.
                skipSslValidation: true
                uri: https://github.com/hkhanworks/spring-cloudembed-repo.git
                default-label: main
#                searchPaths: 'global-properties,{application}'
                searchPaths: '{application}'
